# tasks file for ansible-role-cfn-alb
- name: Create build directory
  file:
    dest: build
    state: directory

- name: Create template
  template:
    src: alb.json.j2
    dest: "build/{{ alb_stack_name }}.json"

- shell: "cat build/{{ alb_stack_name }}.json"

- name: Create or remove role stack
  cloudformation:
    template_parameters:
      VPC: "{{ alb_vpc|default(omit) }}"
      SubnetIDs: "{{ alb_subnets|default(omit) }}"
      SecurityGroups: "{{ alb_sgs }}"
    template: "build/{{alb_stack_name}}.json"
    stack_name: "{{ alb_stack_name }}"
    state: "{{ alb_stack_state }}"
    region: "{{ region|default('us-west-2') }}"
    tags: "{{ alb_tags }}"
  register: alb_cf_output

- debug: msg="{{ alb_cf_output }}" verbosity=1
